# Generated by Django 5.2.6 on 2025-09-30 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerStats', '0012_merge_20250930_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='execution_type',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='execution_type_fk',
            new_name='execution_type',
        ),

        migrations.RemoveField(
            model_name='client',
            name='execution_type_fk',
        ),
    ]
